  on: push
  jobs: 
    job1: 
      runs-on: ubuntu-latest
      steps:
        - run: pwd
        - run: whoami
    job2:
      runs-on: windows-latest
      steps:
        - run: node --version